### ISSUE TITLE
Import bash completions

### ISSUE THREAD

**Issue by andreiborisov** [jorgebucaran/replay.fish#15]
A lot of tools still don't have `fish` completions but do have `bash` completions. It would be cool to be able to write something like this in `config.fish`:

```fish
replay source /usr/local/etc/bash_completion.d/flutter.bash
```

to source `bash` completions.

**Comment by jorgebucaran** [comment]
That would make replay behave like bash on completion, correct?

**Comment by andreiborisov** [comment]
Basically, what I want is to "import" `bash` completions in `fish`. It should be already theoretically possible (I think) by writing `fish` `complete` functions which would just call respected `bash` completions.

What this issue is about whether `replay` could automate that somehow.

**Comment by jorgebucaran** [comment]
I see. What happens if you try to import them right now?

**Comment by andreiborisov** [comment]
Nothing

**Comment by jorgebucaran** [comment]
I get it now. Transforming completions written in Bash into Fish. I'd really like to keep it simple for now, so I'll pass, but who knows!
